Listening to Bitcoin network with Splunk
==============================
This is a simple system for Splunking Bitcoin network and showing interesting metrics for Bitcoin economy. 

It is consisted of two components:

* A Bitcoin node for downloading Bitcoin block chain and listening Bitcoin block chain events via the Bitcoin P2P network
* A [Vagrant](http://www.vagrantup.com/) nvironment for setting up Splunk and importing the Bitcoin logging data generated by the Bitcoin node above

To set it up (only verified under Mac OS X 10.9):

* git clone the Github repository, let's call the repository folder SPLUNKING_BITCOIN_HOME, and call the SPLUNKING_BITCOIN_HOME/src/vagrant/splunk/assets folder ASSETS folder
* Download [Splunk](http://www.splunk.com) Linux x64 for RedHat edition and put it under the ASSETS folder
* Download Bitcoin [bootstrap.dat](http://sourceforge.net/projects/bitcoin/files/Bitcoin/blockchain/) file via BitTorrrent for fast syncing, and put it under ASSETS folder
* Download and install [Vagrant](http://www.vagrantup.com/)
* Download and install [Apache Maven](http://maven.apache.org)
* Enter SPLUNKING_BITCOIN_HOME directory, run "mvn exec:java"
* Copy your Splunk license file to the ASSETS folder and name it splunk.license
* Enter SPLUNKING_BITCOIN_HOME/src/vagrant directory, run "vagrant up"
* That's it, you can use your browser to nagivate to http://192.168.33.2:8089 to use Splunk Web to explore the data